### ISSUE TITLE
ValueError: embedded null character crash in addstr

### ISSUE THREAD

**Issue by ReagentX** [ReagentX/Logria-py#104]
```bash
Traceback (most recent call last):
  File "/Users/chris/.pyenv/versions/3.8.3/bin/logria", line 8, in <module>
    sys.exit(main())
  File "/Users/chris/.pyenv/versions/3.8.3/lib/python3.8/site-packages/logria/__main__.py", line 47, in main
    app.start()
  File "/Users/chris/.pyenv/versions/3.8.3/lib/python3.8/site-packages/logria/communication/shell_output.py", line 248, in start
    curses.wrapper(self.main)
  File "/Users/chris/.pyenv/versions/3.8.3/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/chris/.pyenv/versions/3.8.3/lib/python3.8/site-packages/logria/communication/shell_output.py", line 344, in main
    self.render_text_in_output()
  File "/Users/chris/.pyenv/versions/3.8.3/lib/python3.8/site-packages/logria/communication/shell_output.py", line 165, in render_text_in_output
    color_handler.addstr(self.outwin, current_row, 0, item.rstrip())
  File "/Users/chris/.pyenv/versions/3.8.3/lib/python3.8/site-packages/logria/interface/color_handler.py", line 152, in addstr
    return _inner_addstr(window, string, y_coord, x_coord)
  File "/Users/chris/.pyenv/versions/3.8.3/lib/python3.8/site-packages/logria/interface/color_handler.py", line 123, in _inner_addstr
    _add_line(y_coord, x_coord, window, line)
  File "/Users/chris/.pyenv/versions/3.8.3/lib/python3.8/site-packages/logria/interface/color_handler.py", line 94, in _add_line
    window.addstr(y_coord, x_coord, color_split[0], curses.color_pair(default_color_pair))
ValueError: embedded null character
```

**Comment by ReagentX** [comment]
Sample: [fail-0.txt](https://github.com/ReagentX/Logria/files/4955570/fail-0.txt)

**Comment by ReagentX** [comment]
```
{
    "commands": [
        ["/Users/chris/fail.txt"]
    ],
    "type": "file"
}
```
